version: '3'

services:
  signaling:
    container_name: signaling
    build:
      ./webrtc
    ports:
    - 443:443

  peerjs:
    container_name: peerjs
    build:
      ./webrtc/cert
    ports:
    - 9000:9000

  stun:
    container_name: stun
    build:
      ./stun
    ports:
    - 4040:4040/udp




