version: '3'

services:
  webrtc:
    container_name: webrtc
    build:
      ./webrtc
    ports:
    - 3333:443

  peerjs:
    container_name: peerjs
    build:
      ./webrtc/cert
    ports:
    - 3223:9000

  stun:
    container_name: stun
    build:
      ./stun
    ports:
    - 4040:4040/udp




