version: '3'

services:
  webrtc:
    container_name: webrtc
    build:
      ./webrtc
    ports:
    - 443:443

  stun:
    container_name: stun
    build:
      ./stun
    ports:
    - 4040:4040/udp




